In [1]:
import requests
from pandas.io.json import json_normalize

In [2]:
url = 'https://services.arcgis.com/S9th0jAJ7bqgIRjw/arcgis/rest/services/Neighbourhood_MCI/FeatureServer/0/query?where=1%3D1&outFields=Neighbourhood,Hood_ID,Population,Assault_AVG,AutoTheft_AVG,Homicide_AVG,TheftOver_AVG,BreakandEnter_AVG,Robbery_AVG&outSR=4326&f=json'
results = requests.get(url).json()

In [3]:
crime_data = results['features']
dataframe = json_normalize(crime_data)
dataframe

,attributes.Neighbourhood,attributes.Hood_ID,attributes.Population,attributes.Assault_AVG,attributes.AutoTheft_AVG,attributes.Homicide_AVG,attributes.TheftOver_AVG,attributes.BreakandEnter_AVG,attributes.Robbery_AVG,geometry.rings
0,Yonge-St.Clair,097,12528,31.0,4.3,0.0,4.3,23.3,5.7,"[[[-79.3911544450554, 43.6810810205658], [-79...."
1,York University Heights,027,27593,333.2,106.3,0.8,36.3,113.2,75.8,"[[[-79.5052468371003, 43.7598739861204], [-79...."
2,Lansing-Westgate,038,16164,70.7,23.7,1.7,7.0,38.8,14.7,"[[[-79.4399431314811, 43.7615578229059], [-79...."
3,Yorkdale-Glen Park,031,14804,160.2,55.5,1.2,22.5,63.3,31.5,"[[[-79.4396472248458, 43.7056099782244], [-79...."
4,Stonegate-Queensway,016,25051,83.2,28.7,0.0,6.0,52.8,20.7,"[[[-79.49258326535, 43.6474374941382], [-79.49..."
...,...,...,...,...,...,...,...,...,...,...
135,Milliken,130,26572,83.8,58.5,0.2,16.5,108.3,32.7,"[[[-79.2430336240575, 43.8129695229197], [-79...."
136,Pleasant View,046,15818,46.0,13.5,0.2,3.8,19.8,11.8,"[[[-79.3434143982989, 43.7951654478482], [-79...."
137,Wychwood,094,14349,70.2,13.2,0.3,2.3,34.0,13.8,"[[[-79.4358772262199, 43.680153458125], [-79.4..."
138,Leaside-Bennington,056,16828,32.8,18.2,0.2,5.2,33.3,7.5,"[[[-79.3774491784463, 43.7130919338797], [-79...."
139,Briar Hill-Belgravia,108,14257,73.7,18.2,0.2,5.0,36.7,21.5,"[[[-79.4645812893894, 43.6921560262174], [-79...."

In [4]:
import pandas as pd
df_temp = pd.DataFrame(columns=['ID','Neighborhood'])

In [5]:
df_temp['ID']=dataframe['attributes.Hood_ID']
df_temp['Neighborhood']=dataframe['attributes.Neighbourhood']

In [6]:
df_temp.sort_values(by='ID',inplace=True)

In [7]:
df_temp.reset_index(drop=True,inplace=True)

In [8]:
df_temp

      ID                       Neighborhood
0    001             West Humber-Clairville
1    002  Mount Olive-Silverstone-Jamestown
2    003       Thistletown-Beaumond Heights
3    004                    Rexdale-Kipling
4    005                   Elms-Old Rexdale
..   ...                                ...
135  136                          West Hill
136  137                             Woburn
137  138                      Eglinton East
138  139                Scarborough Village
139  140                          Guildwood

[140 rows x 2 columns]

1-20 Etobicoke 
21-53 North York
54-61 East York
62-105 Central Toronto
106-115 York 
116-140 Scarborough

https://www.realosophy.com/etobicoke-former-toronto/neighbourhood-map
https://www.realosophy.com/north-york-former-toronto/neighbourhood-map
https://www.realosophy.com/east-york-former-toronto/neighbourhood-map
https://www.realosophy.com/central-toronto-former-toronto/neighbourhood-map
https://www.realosophy.com/york-former-toronto/neighbourhood-map
https://www.realosophy.com/scarborough-former-toronto/neighbourhood-map

In [12]:
import requests 
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd

def get_neigh_data(borough):
    url='https://www.realosophy.com/{}-former-toronto/neighbourhood-map'.format(borough)
    driver.get(url)
    time.sleep(5)
    html= driver.page_source

    soup = BeautifulSoup(html,'lxml')
    all_divs = soup.find('div',{'class':'row mt-4'})
    neighborhoods_data = all_divs.find_all('a')

    names = []
    websites = []
    for neighborhood in neighborhoods_data: 
        names.append(neighborhood.text)
        websites.append(neighborhood['href'])
        
    pd.DataFrame({'Names':names,'Websites':websites}).to_csv('{}.csv'.format(borough))
    print('{} done!'.format(borough))

firefoxOptions = Options()
firefoxOptions.add_argument('-headless')
driver = webdriver.Firefox(options=firefoxOptions)

boroughs=['etobicoke','north-york','east-york','central-toronto','york','scarborough']

for borough in boroughs:
    get_neigh_data(borough)

driver.quit()

etobicoke done!
north-york done!
east-york done!
central-toronto done!
york done!
scarborough done!

In [15]:
eto_df=pd.read_csv('etobicoke.csv')
north_df=pd.read_csv('north-york.csv')
east_df=pd.read_csv('east-york.csv')
central_df=pd.read_csv('central-toronto.csv')
york_df=pd.read_csv('york.csv')
scar_df=pd.read_csv('scarborough.csv')

In [22]:
eto_df.head()

,Unnamed: 0,Names,Websites,ID
0,0,Alderwood,/alderwood-toronto/neighbourhood-profile,20
1,1,Centenial Park,/centenial-park-toronto/neighbourhood-profile,11
2,2,Clairville,/clairville-toronto/neighbourhood-profile,1
3,3,Eatonville,/eatonville-toronto/neighbourhood-profile,14
4,4,Etobicoke West Mall,/etobicoke-west-mall-toronto/neighbourhood-pro...,13

In [49]:
neigh_id_website_df = pd.concat([eto_df,north_df,east_df,central_df,york_df,scar_df])

In [50]:
neigh_id_website_df.drop(['Unnamed: 0','Names'],axis=1,inplace=True)
neigh_id_website_df.sort_values('ID',inplace=True)
neigh_id_website_df.reset_index(drop=True,inplace=True)

In [40]:
neigh_id_website_df.to_csv('neigh_id_website.csv')

In [51]:
neigh_id_website_df.head()

                                     Websites  ID
0   /clairville-toronto/neighbourhood-profile   1
1   /smithfield-toronto/neighbourhood-profile   2
2  /thistletown-toronto/neighbourhood-profile   3
3      /rexdale-toronto/neighbourhood-profile   4
4     /the-elms-toronto/neighbourhood-profile   5

In [52]:
neigh_id_website_df['Avg House Price']=0
neigh_id_website_df['Avg Income']=0
neigh_id_website_df.head()

                                     Websites  ID  Avg House Price  Avg Income
0   /clairville-toronto/neighbourhood-profile   1                0           0
1   /smithfield-toronto/neighbourhood-profile   2                0           0
2  /thistletown-toronto/neighbourhood-profile   3                0           0
3      /rexdale-toronto/neighbourhood-profile   4                0           0
4     /the-elms-toronto/neighbourhood-profile   5                0           0

In [66]:
def get_number_only(variable):
    clear_space = variable.text.strip()
    clear_dollarsign = clear_space.replace('$','')
    clear_character = clear_dollarsign.replace(',','')
    if 'M' in clear_character:
        string = clear_character.replace('M','')
        number = float(string)
        result = int(number*1000000)
        return result
    else:
        string = clear_character.replace('K','')
        number = int(string)
        result = number*1000
        return result

In [67]:
import requests 
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.keys import Keys
import time
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

firefoxOptions = Options()
firefoxOptions.add_argument('-headless')
driver = webdriver.Firefox(options=firefoxOptions)

for i in range(len(neigh_id_website_df['Websites'])):
    url='https://www.realosophy.com{}'.format(neigh_id_website_df['Websites'][i])
    driver.get(url)
    time.sleep(5)
    html= driver.page_source

    soup = BeautifulSoup(html,'lxml')
    avg_house_price_data = soup.find('div',{'class':'key-stats__avg-sale-price ng-binding ng-scope'})        
    avg_income_data = soup.find('p',{'class': 'h3 font-sans-caption-bold mb-0 text-center text-sm-left ng-binding ng-scope'})

    while avg_house_price_data == None or avg_income_data == None:
        url='https://www.realosophy.com{}'.format(neigh_id_website_df['Websites'][i])
        driver.get(url)
        time.sleep(5)
        html= driver.page_source

        soup = BeautifulSoup(html,'lxml')
        avg_house_price_data = soup.find('div',{'class':'key-stats__avg-sale-price ng-binding ng-scope'})        
        avg_income_data = soup.find('p',{'class': 'h3 font-sans-caption-bold mb-0 text-center text-sm-left ng-binding ng-scope'})
    
    neigh_id_website_df['Avg House Price'][i] = get_number_only(avg_house_price_data)
    neigh_id_website_df['Avg Income'][i] = get_number_only(avg_income_data)
    
    print(neigh_id_website_df['ID'][i])
    
driver.quit()

<ipython-input-67-e374f1d55647>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  neigh_id_website_df['Avg House Price'][i] = get_number_only(avg_house_price_data)
<ipython-input-67-e374f1d55647>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  neigh_id_website_df['Avg Income'][i] = get_number_only(avg_income_data)

1
2
3
4
5
6
7
8
9
10
11
11
12
13
14
14
14
15
16
16
17
17
18
19
20
21
22
23
23
24
25
26
27
28
29
30
31
31
32
33
34
35
36
37
38
38
39
39
39
40
41
41
41
41
42
42
43
43
44
45
45
45
46
47
48
49
50
51
52
53
54
54
54
55
56
56
57
58
59
60
61
62
63
64
65
66
67
67
68
69
70
70
71
72
73
73
73
74
74
75
75
76
76
77
77
77
77
77
77
77
77
77
78
78
78
79
80
81
81
82
82
82
83
83
84
85
86
87
87
88
89
90
90
91
92
92
93
93
93
93
94
95
95
95
96
96
96
97
97
98
98
99
100
101
102
103
103
103
104
105
105
106
107
108
109
110
111
112
113
114
114
114
115
116
117
118
119
119
120
120
121
122
122
123
124
125
126
127
128
129
130
131
131
132
133
134
135
135
136
137
138
139
140

In [71]:
neigh_id_website_df.to_csv('neigh_houseprice_raw.csv')

In [74]:
neigh_houseprice_raw = neigh_id_website_df.groupby('ID').mean()

In [78]:
neigh_houseprice_raw['Avg House Price']=neigh_houseprice_raw['Avg House Price'].astype(int)

In [80]:
neigh_houseprice_raw['Avg Income']=neigh_houseprice_raw['Avg Income'].astype(int)

In [88]:
neigh_houseprice_raw.to_csv('neigh_houseprice_grouped.csv')